services:
  quioscodb:
    image: postgres
    restart: always
    
    environment:
      POSTGRES_DB: quiosco-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    container_name: quiosco-database
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data